config/routes.rb
Rails.application.routes.draw do
 
  root 'pages#home'  
  
  get '/home', to: 'pages#home'

  #get '/recipes', to:'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post '/recipes', to: 'recipes#create', as: 'create_recipe'
  #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
  #get '/recipes/:id', to: 'recipes#show', as: 'show_recipe'
  #delete '/recipes/:id', to: 'recipes#destroy', as: 'delete_recipe'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  get '/register', to: 'chefs#new'
  
  get '/login', to: "logins#new"
  post 'login', to: "logins#create"
  get 'logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1> Welcome to Maret Recipes Application</h1>
  <h2> Create, Browse, Like and dislike recipes</h2>
  <%= link_to "sign up now!", register_path, class: "btn btn-lg btn-success" %>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as a Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
    <p><%= link_to "Browse Recipe Listings", recipes_path,class: "btn btn-warning btn-small" %></p>
  </div>
    <div class="col-lg-4">
    <h3 class="midrow">
      Sign in to your account
    </h3>
    <h2 class="left">Add/update your recipes/create reviews/like-dislike recipes and more !</h2>
    <p><%= link_to "Login to your account", "",class: "btn btn-warning btn-small" %></p>
  </div>
    <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as a Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and sign up later</h2>
    <p><%= link_to "Browse Recipe Listings", "" ,class: "btn btn-warning btn-small" %></p>
  </div>
</div>